[Game]
# デフォルト値です。 CgfGoBan などの GUI はこのファイルを見ません

# Komi - コミ☆（＾～＾）
Komi = 6.5

# BoardSize - 何路盤。
BoardSize = 9

# MaxMoves - 最大手数。
MaxMoves = 1000

BoardData = '''
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 0, 1, 1, 1, 0, 2, 2, 2, 0, 3,
	3, 1, 1, 1, 1, 1, 2, 2, 2, 2, 3,
	3, 1, 1, 1, 1, 1, 2, 2, 2, 2, 3,
	3, 1, 1, 1, 1, 1, 2, 2, 2, 2, 3,
	3, 0, 2, 2, 2, 0, 2, 2, 2, 0, 3,
	3, 2, 2, 2, 2, 1, 1, 1, 1, 1, 3,
	3, 2, 2, 2, 2, 1, 1, 1, 1, 1, 3,
	3, 2, 2, 2, 2, 1, 1, 1, 1, 1, 3,
	3, 0, 2, 2, 2, 0, 1, 1, 1, 0, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
'''
